# Generated by Django 4.2.5 on 2023-12-14 17:34

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0002_alter_accountdata_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedhosts',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
