# Generated by Django 4.2.5 on 2023-12-14 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('terminal', '0003_savedhosts_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the data.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the data was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the data was last updated.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SSHData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the data.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the data was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the data was last updated.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='savedhosts',
            name='user',
            field=models.ForeignKey(default=None, help_text='The user associated with the saved host.', on_delete=django.db.models.deletion.CASCADE, related_name='saved_hosts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SessionsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.CharField(help_text='User permissions for the session.', max_length=50)),
                ('sharing_enabled', models.BooleanField(default=False, help_text='Flag indicating if sharing is enabled for the session.')),
                ('session_closed', models.BooleanField(default=False, help_text='Flag indicating if the session is closed.')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('connected_user', models.ForeignKey(help_text='The user connected to the session.', on_delete=django.db.models.deletion.CASCADE, related_name='connected_sessions', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='The user associated with the session.', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
