# Generated by Django 4.2.5 on 2023-12-15 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0007_sessionslist_color_alter_savedhost_passphrase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesdata',
            name='session',
        ),
        migrations.RemoveField(
            model_name='savedhost',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='sshdata',
            name='session',
        ),
    ]
