# Generated by Django 4.2.5 on 2023-12-15 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('terminal', '0008_remove_notesdata_session_remove_savedhost_public_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionslist',
            name='content_type',
            field=models.ForeignKey(default=None, limit_choices_to={'model__in': ['sshdata', 'notesdata']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessionslist',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
