# Generated by Django 4.2.5 on 2023-12-15 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('terminal', '0010_alter_sessionslist_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionslist',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['sshdata', 'notesdata']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
