# Generated by Django 4.2.5 on 2023-12-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0011_alter_sessionslist_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesdata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sshdata',
            name='name',
        ),
        migrations.AddField(
            model_name='sessionslist',
            name='name',
            field=models.CharField(default='Session', help_text='Name of the data.', max_length=100),
        ),
    ]
