# Generated by Django 4.2.5 on 2024-01-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0014_alter_sessionslist_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdata',
            name='email',
            field=models.EmailField(help_text='The email address of the user.', max_length=40),
        ),
    ]
