# Generated by Django 4.2.5 on 2024-01-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0016_alter_notesdata_session_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesdata',
            name='session_lock',
            field=models.BooleanField(default=True, help_text='This flags informs if other session users (except master) can iteract with terminal'),
        ),
        migrations.AddField(
            model_name='notesdata',
            name='session_open',
            field=models.BooleanField(default=False, help_text='This flags informs if other users can join this session'),
        ),
        migrations.AddField(
            model_name='sshdata',
            name='session_lock',
            field=models.BooleanField(default=True, help_text='This flags informs if other session users (except master) can iteract with terminal'),
        ),
        migrations.AddField(
            model_name='sshdata',
            name='session_open',
            field=models.BooleanField(default=False, help_text='This flags informs if other users can join this session'),
        ),
    ]
