# Generated by Django 4.2.5 on 2024-01-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0017_notesdata_session_lock_notesdata_session_open_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedhost',
            name='ip_address_v4',
        ),
        migrations.RemoveField(
            model_name='savedhost',
            name='ip_address_v6',
        ),
        migrations.AddField(
            model_name='savedhost',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='The IP address of the saved host.', null=True),
        ),
        migrations.AlterField(
            model_name='savedhost',
            name='hostname',
            field=models.CharField(blank=True, help_text='The hostname of the saved host.', max_length=255, null=True),
        ),
    ]
