# Generated by Django 4.2.5 on 2024-01-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0018_remove_savedhost_ip_address_v4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedhost',
            name='name',
            field=models.CharField(default='Session', help_text='Default name of the tab in fronend.', max_length=100),
        ),
    ]
