# Generated by Django 4.2.5 on 2024-01-06 20:26

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0019_savedhost_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedhost',
            old_name='ip_address',
            new_name='ip',
        ),
        migrations.AlterField(
            model_name='savedhost',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', help_text='Tab color', image_field=None, max_length=25, samples=[('#BA1C1C', 'Correl Red'), ('#2E9329', 'Forest Green'), ('#248BC2', 'Deep Blue'), ('#BD2DB6', 'Steel Pink'), ('#E0A61E', 'Harvest Gold')]),
        ),
    ]
