# Generated by Django 4.2.5 on 2024-01-08 23:23

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0020_rename_ip_address_savedhost_ip_alter_savedhost_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshdata',
            name='hostname',
            field=models.CharField(blank=True, help_text='The hostname of the host.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sshdata',
            name='ip',
            field=models.GenericIPAddressField(blank=True, help_text='The IP address of the host.', null=True),
        ),
        migrations.AddField(
            model_name='sshdata',
            name='port',
            field=models.PositiveIntegerField(blank=True, default=22, help_text='The port number for accessing the host.', null=True),
        ),
        migrations.AlterField(
            model_name='sessionslist',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', help_text='Tab color', image_field=None, max_length=25, samples=[('#BA1C1C', 'Correl Red'), ('#2E9329', 'Forest Green'), ('#248BC2', 'Deep Blue'), ('#BD2DB6', 'Steel Pink'), ('#E0A61E', 'Harvest Gold')]),
        ),
    ]
