# Generated by Django 4.2.5 on 2024-01-11 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0022_alter_savedhost_color_alter_sessionslist_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshdata',
            name='save_session',
            field=models.ForeignKey(blank=True, default=None, help_text='Saved Host data reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sshdate', to='terminal.savedhost'),
        ),
    ]
