# Generated by Django 4.2.5 on 2024-01-11 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0023_sshdata_content'),
        ('terminal', '0023_sshdata_save_session'),
    ]

    operations = [
    ]
