# Generated by Django 4.2.5 on 2024-01-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0023_sshdata_save_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesdata',
            name='session_key',
            field=models.CharField(blank=True, default=None, help_text='This key is use in session sharing', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sshdata',
            name='session_key',
            field=models.CharField(blank=True, default=None, help_text='This key is use in session sharing', max_length=500, null=True),
        ),
    ]
