# Generated by Django 4.2.5 on 2024-01-12 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0024_merge_0023_sshdata_content_0023_sshdata_save_session'),
        ('terminal', '0025_alter_sessionslist_unique_together'),
    ]

    operations = [
    ]
