# Generated by Django 4.2.5 on 2024-01-13 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0023_sshdata_content'),
        ('terminal', '0025_alter_sessionslist_unique_together'),
    ]

    operations = [
    ]
