# Generated by Django 4.2.5 on 2024-01-14 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0026_merge_20240112_0158'),
        ('terminal', '0026_merge_20240113_1955'),
    ]

    operations = [
    ]
