# Generated by Django 4.2.5 on 2024-01-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('terminal', '0027_merge_20240114_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesdata',
            name='content',
            field=models.JSONField(blank=True, default=None, help_text='All note content for this note session'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionslist',
            unique_together={('user', 'content_type', 'object_id')},
        ),
    ]
