# Generated by Django 4.2.5 on 2024-01-15 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('terminal', '0027_merge_20240114_0118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notesdata',
            options={'permissions': [('USE_NOTE', 'This permission give user ability to use notes funcjonality')]},
        ),
        migrations.AlterModelOptions(
            name='sshdata',
            options={'permissions': [('USE_SSH', 'This permission give user ability to use SSH funcjonality')]},
        ),
        migrations.AlterUniqueTogether(
            name='sessionslist',
            unique_together={('user', 'content_type', 'object_id')},
        ),
    ]
