# Generated by Django 4.2.5 on 2024-01-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0028_notesdata_content_alter_sessionslist_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesdata',
            name='content',
            field=models.JSONField(blank=True, default=None, help_text='All note content for this note session', null=True),
        ),
    ]
