# Generated by Django 4.2.5 on 2024-01-16 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0028_alter_notesdata_options_alter_sshdata_options_and_more'),
        ('terminal', '0029_alter_notesdata_content'),
    ]

    operations = [
    ]
